server:
  port: 8080
  
spring:
  application:
    name: my-app
  datasource:
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    url: jdbc:${DB_URL}
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
logging:
  level:
    org.hibernate.engine.jdbc.env.internal.LobCreatorBuilderImpl: ERROR

